name: test

on:
  push:
    branches: ['**']
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'test/**'
      - 'package*.json'
      - 'tsconfig*.json'
      - '.npmrc'
  pull_request:
    branches: [main]
    paths:
      # no way to avoid repeating the paths here
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'test/**'
      - 'package*.json'
      - 'tsconfig*.json'
      - '.npmrc'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npm test
